// Generated by CoffeeScript 1.8.0
(function() {
  var Base64, assert;

  assert = require('assert');

  Base64 = require('../base64');

  describe('gcd_tests', function() {
    return describe('test gcd', function() {
      it('should calculate the gcd with 1 correctly', function() {
        var check_with_1;
        check_with_1 = function(num) {
          var base, gcd, num1;
          base = Base64.toBase64(num);
          num1 = Base64.toBase64(1);
          gcd = Base64.gcd(num1, base);
          return assert.equal(gcd, num1);
        };
        check_with_1(1);
        check_with_1(2);
        return check_with_1(1234567890);
      });
      return it('should calculate the gcd correctly', function() {
        var check_gcd;
        check_gcd = function(num1, num2, expected) {
          var gcd;
          num1 = Base64.toBase64(num1);
          num2 = Base64.toBase64(num2);
          expected = Base64.toBase64(expected);
          gcd = Base64.gcd(num1, num2);
          return assert.equal(gcd, expected);
        };
        check_gcd(2, 2, 2);
        check_gcd(1234567890, 126, 18);
        check_gcd(1234, 12345, 1);
        return check_gcd(32, 64, 32);
      });
    });
  });

}).call(this);
