// Generated by CoffeeScript 1.8.0
(function() {
  var Base64, assert;

  assert = require('assert');

  Base64 = require('../base64');

  describe('lcm_tests', function() {
    return describe('test lcm', function() {
      it('should calculate the lcm with 1 correctly', function() {
        var check_with_1;
        check_with_1 = function(num) {
          var base, lcm, num1;
          base = Base64.toBase64(num);
          num1 = Base64.toBase64(1);
          lcm = Base64.lcm(num1, base);
          return assert.equal(lcm, base);
        };
        check_with_1(1);
        check_with_1(2);
        return check_with_1(1234567890);
      });
      return it('should calculate the lcm correctly', function() {
        var check_lcm;
        check_lcm = function(num1, num2, expected) {
          var lcm;
          num1 = Base64.toBase64(num1);
          num2 = Base64.toBase64(num2);
          expected = Base64.toBase64(expected);
          lcm = Base64.lcm(num1, num2);
          return assert.equal(lcm, expected);
        };
        check_lcm(2, 2, 2);
        check_lcm(2350, 125, 11750);
        check_lcm(1234, 12345, 15233730);
        return check_lcm(32, 64, 64);
      });
    });
  });

}).call(this);
